### ISSUE TITLE
Docker로 Spring Boot + MySQL 컨테이너 구성

### ISSUE THREAD

**Issue by sehyeogg365** [sehyeogg365/WE-Library#36]

**Comment by sehyeogg365** [comment]
docker-compose.yml
```
# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: welibrary
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  springboot-app:
    build: .
    container_name: welibrary-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/welibrary?serverTimezone=Asia/Seoul&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure

volumes:
  dbdata:
```

**Comment by sehyeogg365** [comment]
application-docker.yml
```
# application-docker.yml (Docker 실행 시 사용될 설정)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/welibrary?serverTimezone=Asia/Seoul
    username: root
    password: root
```
